version: '3'
services:
  # condo-questionnaire-api.test:
  #   build:
  #       context: ./TownhomeQuestionnaire.API
  #       dockerfile: Dockerfile
  #   image: condo-questionnaire-api/api
  #   extra_hosts:
  #       - 'host.docker.internal:host-gateway'
  #   ports:
  #       - '${APP_PORT:-80}:80'
  #   volumes:
  #       - './TownhomeQuestionnaire.API:/var/www/html:delegated'
  #   networks:
  #       - condo-questionnaire-app
  #   depends_on:
  #       - postgres-postgis
  #       - redis
  #       -elastic-search
  
  condo-questionnaire-api.migration:
    build:
      context: ./CondoQuestionnaire.Migration
      dockerfile: Dockerfile
    image: condo-questionnaire-api/migration
    extra_hosts:
      - 'host.docker.internal:host-gateway'  
    volumes:
      - './TownhomeQuestionnaire.API:/var/www/html:delegated'
    networks:
      - condo-questionnaire-app
    depends_on:
      - postgres
  
  redis:
    build: ./docker-compose/redis
    restart: unless-stopped
    command: redis-server # --requirepass ${REDIS_PASSWORD}
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - ${APP_DATA_PATH:-.}/data/redis:/data
    networks:
      - condo-questionnaire-app
  
  elasticsearch:
    restart: unless-stopped
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELK_VERSION:-7.10.2}
    volumes:
      - ${APP_DATA_PATH:-.}/data/elastic-search/data:/usr/share/elasticsearch/data
    environment:
      - cluster.name=${ES_CLUSTER_NAME:-conso-questionnaire}
      - node.name=${ES_CLUSTER_NAME:-conso-questionnair}-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms128m -Xmx128m"
      - cluster.initial_master_nodes=${ES_CLUSTER_NAME:-conso-questionnair}-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "${ELASTICSEARCH_HOST_HTTP_PORT:-9200}:9200"
      - "${ELASTICSEARCH_HOST_TRANSPORT_PORT:-9300}:9300"
    networks:
      - condo-questionnaire-app
  
  pgAdmin:
    image: dpage/pgadmin4:6.14
    environment:
      - PGADMIN_DEFAULT_PASSWORD=SuperSecret
      - PGADMIN_DEFAULT_EMAIL=dev@mail.com
    ports:
      - "5050:80"
    volumes:
      - ${APP_DATA_PATH:-.}/data/pgAdmin:/var/lib/pgadmin
    networks:
      - condo-questionnaire-app
  
  postgres:
    image: postgres:14.1-alpine
    restart: unless-stopped
    volumes:
      - ${APP_DATA_PATH:-.}/data/postgres:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT-5432}:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-postgres}
      - POSTGRES_USER=${POSTGRES_USER:-default}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-secret}
    networks:
      - condo-questionnaire-app

networks:
  condo-questionnaire-app:
    driver: bridge